DELETE FROM Resultados;
DELETE FROM Penaltis;
DELETE FROM Prolongamento;
DELETE FROM Substituicao;
DELETE FROM Falta;
DELETE FROM Golo;
DELETE FROM Evento;
DELETE FROM Jogo;
DELETE FROM Grupo;
DELETE FROM Fase;
DELETE FROM Arbitro;
DELETE FROM Jogador;
DELETE FROM Estadio;
DELETE FROM Equipa;

INSERT INTO Equipa VALUES(1,'Mvd Cty Torque','Lucas Nardi', 'Uruguai',99,0);
INSERT INTO Equipa VALUES(2,'Barcelona SC','Fabián Bustos', 'Equador',18,0);
INSERT INTO Equipa VALUES(3,'Deportivo Lara','Jesús Ortíz', 'Venezuela',75,0);
INSERT INTO Equipa VALUES(4,'Bolívar La Paz','Beñat San José', 'Bolívia',31,0);
INSERT INTO Equipa VALUES(5,'Olimpia','Julio Cáceres', 'Paraguai',14,0);
INSERT INTO Equipa VALUES(6,'César Vallejo','José del Solar', 'Perú',141,0);

INSERT INTO Equipa VALUES(7,'Everton','Francisco Meneghini', 'Chile',165,0);
INSERT INTO Equipa VALUES(8,'Monagas SC','Jhonny Ferreira', 'Venezuela',133,0);
INSERT INTO Equipa VALUES(9,'Plaza Colonia','Alejandro Cappuccio', 'Uruguai',205,0);
INSERT INTO Equipa VALUES(10,'The Strongest','Claudio Biaggio', 'Bolívia',40,0);
INSERT INTO Equipa VALUES(11,'Millonarios','Alberto Gamero', 'Colômbia',52,0);
INSERT INTO Equipa VALUES(12,'Fluminense','Fernando Diniz', 'Brasil',30,0);
INSERT INTO Equipa VALUES(13,'América-MG','Vagner Mancini', 'Brasil',269,0);
INSERT INTO Equipa VALUES(14,'Guaraní','Fernando Jubero', 'Paraguai',38,0);
INSERT INTO Equipa VALUES(15,'CD Universidad Católica','Miguel Rondelli', 'Equador',120,0);
INSERT INTO Equipa VALUES(16,'Audax Italiano','Fernando Solís', 'Chile',152,0);
INSERT INTO Equipa VALUES(17,'Estudiantes','Pablo Quattrocchi', 'Argentina',34,0);
INSERT INTO Equipa VALUES(18,'Universitario','Carlos Compagnucci', 'Perú',43,0);
INSERT INTO Equipa VALUES(19,'Atlético Nacional','Paulo Autuori', 'Colômbia',9,0);

INSERT INTO Equipa VALUES(20,'Palmeiras','Abel Ferreira', 'Brasil',2,1);
INSERT INTO Equipa VALUES(21,'Emelec','Ismael Rescalvo', 'Equador',28,1);
INSERT INTO Equipa VALUES(22,'Deportivo Tachira','Eduardo Saragó', 'Venezuela',46,1);
INSERT INTO Equipa VALUES(23,'Independiente Petrolero','Rodrigo Venegas', 'Bolívia',178,1);
INSERT INTO Equipa VALUES(24,'Libertad','Daniel Garnero', 'Paraguai',16,1);
INSERT INTO Equipa VALUES(25,'Athletico-PR','Luiz Felipe Scolari', 'Brasil',12,1);
INSERT INTO Equipa VALUES(26,'Caracas FC','Leo González', 'Venezuela',67,1);
INSERT INTO Equipa VALUES(27,'Vélez Sarsfield','Alexander Medina', 'Argentina',33,1);
INSERT INTO Equipa VALUES(28,'Nacional','Pablo Repetto', 'Uruguai',6,1);
INSERT INTO Equipa VALUES(29,'RB Bragantino','Marcinho', 'Brasil',45,1);
INSERT INTO Equipa VALUES(30,'Atlético-MG','Cuca', 'Brasil',11,1);
INSERT INTO Equipa VALUES(31,'Deportes Tolima','Hernán Torres', 'Colômbia',60,1);
INSERT INTO Equipa VALUES(32,'Independiente del Valle','Martín Anselmi', 'Equador',21,1);
INSERT INTO Equipa VALUES(33,'Boca Juniors','Hugo Ibarra', 'Argentina',3,1);
INSERT INTO Equipa VALUES(34,'Corinthians','Vítor Pereira', 'Brasil',29,1);
INSERT INTO Equipa VALUES(35,'Deportivo Cali','Jorge Luís Pinto', 'Colômbia',444,1);
INSERT INTO Equipa VALUES(36,'Always Ready','Óscar Villegas', 'Bolívia',86,1);
INSERT INTO Equipa VALUES(37,'River Plate','Marcelo Gallardo', 'Argentina',1,1);
INSERT INTO Equipa VALUES(38,'Fortaleza','Juan Pablo Vojvoda', 'Brasil',229,1);
INSERT INTO Equipa VALUES(39,'Colo Colo','Gustavo Quinteros', 'Chile',32,1);
INSERT INTO Equipa VALUES(40,'Alianza Lima','Guillermo Salas', 'Perú',54,1);
INSERT INTO Equipa VALUES(41,'Colón','Marcelo Saralegui', 'Argentina',64,1);
INSERT INTO Equipa VALUES(42,'Cerro Porteño','Francisco Arce', 'Paraguai',15,1);
INSERT INTO Equipa VALUES(43,'Peñarol','Mauricio Larriera', 'Uruguai',7,1);
INSERT INTO Equipa VALUES(44,'Flamengo','Dorival Júnior', 'Brasil',4,1);
INSERT INTO Equipa VALUES(45,'Sporting Cristal','Roberto Mosquera', 'Perú',35,1);
INSERT INTO Equipa VALUES(46,'U. Católica','Ariel Holan', 'Chile',26,1);
INSERT INTO Equipa VALUES(47,'Talleres','Javier Gandolfi', 'Argentina',105,1);



INSERT INTO Arbitro VALUES(1,'Néstor Pitana','Argentina');
INSERT INTO Arbitro VALUES(2,'Wilton Sampaio','Brasil');
INSERT INTO Arbitro VALUES(3,'Wilmar Roldán','Colômbia');  
INSERT INTO Arbitro VALUES(4,'Patricio Loustau','Argentina');
INSERT INTO Arbitro VALUES(5,'Roberto Tobar','Chile');
INSERT INTO Arbitro VALUES(6,'Andrés Cunha','Uruguai');
INSERT INTO Arbitro VALUES(7,'Piero Maza','Chile');
INSERT INTO Arbitro VALUES(8,'Anderson Daronco','Brasil');


INSERT INTO Estadio VALUES(1,'Mvd Cty Torque','Estadio Charrúa', 'Montevideo', 14000);
INSERT INTO Estadio VALUES(2,'Barcelona SC','Monumental Banco Pichincha', 'Guayaquil', 57267);
INSERT INTO Estadio VALUES(3,'Deportivo Lara','Estadio Farid Richa', 'Barquisimeto', 12480);
INSERT INTO Estadio VALUES(4,'Bolívar La Paz','Estadio Hernando Siles', 'La Paz', 42000);
INSERT INTO Estadio VALUES(5,'Olimpia','Estadio Manuel Ferreira', 'Asunción', 	20000);
INSERT INTO Estadio VALUES(6,'César Vallejo','Estadio Mansiche', 'Trujillo', 24000);
INSERT INTO Estadio VALUES(7,'Everton','Estadio Sausalito', 'Viña del Mar', 23423);
INSERT INTO Estadio VALUES(8,'Monagas SC','Estadio Monumental de Maturín', 'Maturín', 51796);
INSERT INTO Estadio VALUES(9,'Plaza Colonia','Parque Cincuentenario Juan Gaspar Prandi', 'Colonia del Sacramento', 3000);
INSERT INTO Estadio VALUES(10,'The Strongest','Estadio Hernando Siles', 'La Paz', 42000);
INSERT INTO Estadio VALUES(11,'Millonarios','Estadio Nemesio Camacho', 'Bogotá', 36343);
INSERT INTO Estadio VALUES(12,'Fluminense','Estádio Jornalista Mário Filho', 'Rio de Janeiro', 82238);
INSERT INTO Estadio VALUES(13,'América-MG','Estádio Raimundo Sampaio', 'Belo Horizonte', 25000);
INSERT INTO Estadio VALUES(14,'Guaraní','Estadio Rogelio Livieres', 'Asunción', 8000);
INSERT INTO Estadio VALUES(15,'CD Universidad Católica','Olímpico Atahualpa', 'Quito', 39861);
INSERT INTO Estadio VALUES(16,'Audax Italiano','Bicentenario de La Florida', 'Santiago', 12000);
INSERT INTO Estadio VALUES(17,'Estudiantes','Jorge Luis Hirschi', 'La Plata', 32530);
INSERT INTO Estadio VALUES(18,'Universitario','Estadio Monumental de Lima', 'Lima', 80093);
INSERT INTO Estadio VALUES(19,'Atlético Nacional','Estadio Atanasio Girardot', 'Medellín', 45943);
INSERT INTO Estadio VALUES(20,'Palmeiras','Allianz Parque', 'São Paulo', 43600);
INSERT INTO Estadio VALUES(21,'Emelec','Estadio George Capwell', 'Guayaquil', 40000);
INSERT INTO Estadio VALUES(22,'Deportivo Tachira','Estadio Polideportivo de Pueblo Nuevo', 'San Cristóbal', 38755);
INSERT INTO Estadio VALUES(23,'Independiente Petrolero','Estadio Olímpico Patria', 'Sucre', 30700);
INSERT INTO Estadio VALUES(24,'Libertad','Estadio Dr. Nicolás Léoz', 'Asunción', 10000);
INSERT INTO Estadio VALUES(25,'Athletico-PR','Arena da Baixada', 'Curitiba', 42372);
INSERT INTO Estadio VALUES(26,'Caracas FC','Estadio Olímpico de la Ciudad Universitaria', 'Caracas', 23940);
INSERT INTO Estadio VALUES(27,'Vélez Sarsfield','José Amalfitani', 'Buenos Aires', 49747);
INSERT INTO Estadio VALUES(28,'Nacional','Gran Parque Central', 'Montevideo', 34000);
INSERT INTO Estadio VALUES(29,'RB Bragantino','Estádio Nabi Abi Chedid', 'Bragança Paulista', 13212);
INSERT INTO Estadio VALUES(30,'Atlético-MG','Estádio Raimundo Sampaio', 'Belo Horizonte', 23018);
INSERT INTO Estadio VALUES(31,'Deportes Tolima','Estadio Manuel Murillo Toro', 'Ibagué', 28100);
INSERT INTO Estadio VALUES(32,'Independiente del Valle','Estadio Banco Guayaquil', 'Amaguaña', 12000);
INSERT INTO Estadio VALUES(33,'Boca Juniors','Alberto J. Armando', 'Buenos Aires', 57200);
INSERT INTO Estadio VALUES(34,'Corinthians','Neo Química Arena', 'São Paulo', 49205);
INSERT INTO Estadio VALUES(35,'Deportivo Cali','Estadio Deportivo Cali', 'Palmira', 52000);
INSERT INTO Estadio VALUES(36,'Always Ready','Estadio Municipal El Alto', 'El Alto', 25000);
INSERT INTO Estadio VALUES(37,'River Plate','Mâs Monumental', 'Buenos Aires', 72054);
INSERT INTO Estadio VALUES(38,'Fortaleza','Estádio Governador Plácido Castelo', 'Fortaleza', 60326);
INSERT INTO Estadio VALUES(39,'Colo Colo','Monumental David Arellano', 'Santiago', 47347);
INSERT INTO Estadio VALUES(40,'Alianza Lima','Estadio Alejandro Villanueva', 'Lima', 33938);
INSERT INTO Estadio VALUES(41,'Colón','B. G. Estanislao López', 'Santa Fe', 40000);
INSERT INTO Estadio VALUES(42,'Cerro Porteño','Estadio General Pablo Rojas', 'Asunción', 45000);
INSERT INTO Estadio VALUES(43,'Peñarol','Campeón del Siglo', 'Montevideo', 40700);
INSERT INTO Estadio VALUES(44,'Flamengo','Estádio Jornalista Mário Filho', 'Rio de Janeiro', 82238);
INSERT INTO Estadio VALUES(45,'Sporting Cristal','Estadio Alberto Gallardo', 'Lima', 18000);
INSERT INTO Estadio VALUES(46,'U. Católica','San Carlos de Apoquindo', 'Santiago', 14768);
INSERT INTO Estadio VALUES(47,'Talleres','Mario Alberto Kempes', 'Córdoba', 55144);

INSERT INTO Jogador VALUES(1,'Bento',23, 'Brasil','GK', 'Athletico-PR');
INSERT INTO Jogador VALUES(2,'Anderson Paixão',24, 'Brasil','GK', 'Athletico-PR');
INSERT INTO Jogador VALUES(3,'Pedro Henrique',27, 'Brasil','CB', 'Athletico-PR');
INSERT INTO Jogador VALUES(4,'Thiago Heleno',34, 'Brasil','CB', 'Athletico-PR');
INSERT INTO Jogador VALUES(5,'Matheus Felipe',24, 'Brasil','CB', 'Athletico-PR');
INSERT INTO Jogador VALUES(6,'Nicolás Hernández',24, 'Colômbia','CB', 'Athletico-PR');
INSERT INTO Jogador VALUES(7,'Abner',22, 'Brasil','LB', 'Athletico-PR');
INSERT INTO Jogador VALUES(8,'Pedrinho',20, 'Brasil','LB', 'Athletico-PR');
INSERT INTO Jogador VALUES(9,'Khellven',21, 'Brasil','RB', 'Athletico-PR');
INSERT INTO Jogador VALUES(10,'Luis Orejuela',27, 'Colômbia','RB', 'Athletico-PR');
INSERT INTO Jogador VALUES(11,'Hugo Moura',24, 'Brasil','CDM', 'Athletico-PR');
INSERT INTO Jogador VALUES(12,'Fernandinho',37, 'Brasil','CDM', 'Athletico-PR');
INSERT INTO Jogador VALUES(13,'Christian',21, 'Brasil','CM', 'Athletico-PR');
INSERT INTO Jogador VALUES(14,'Erick',25, 'Brasil','CM', 'Athletico-PR');
INSERT INTO Jogador VALUES(15,'Léo Cittadini',28, 'Brasil','CM', 'Athletico-PR');
INSERT INTO Jogador VALUES(16,'Alex Santana',27, 'Brasil','CN', 'Athletico-PR');
INSERT INTO Jogador VALUES(17,'Matheus Fernandes',24, 'Brasil','CM', 'Athletico-PR');
INSERT INTO Jogador VALUES(18,'Bryan García',21, 'Equador','CM', 'Athletico-PR');
INSERT INTO Jogador VALUES(19,'David Terans',28, 'Uruguai','CAM', 'Athletico-PR');
INSERT INTO Jogador VALUES(20,'Vitinho',23, 'Brasil','LW', 'Athletico-PR');      
INSERT INTO Jogador VALUES(21,'Tomás Cuello',22, 'Argentina','LW', 'Athletico-PR');
INSERT INTO Jogador VALUES(22,'Agustín Canobbio',24, 'Uruguai','RW', 'Athletico-PR');  
INSERT INTO Jogador VALUES(23,'Marlos',34, 'Ucrânia','RW', 'Athletico-PR'); 
INSERT INTO Jogador VALUES(24,'Marcelo Cirino',30, 'Brasil','RW', 'Athletico-PR');   
INSERT INTO Jogador VALUES(25,'Vitor Bueno',28, 'Brasil','CF', 'Athletico-PR'); 
INSERT INTO Jogador VALUES(26,'Vitor Roque',17, 'Brasil','ST', 'Athletico-PR'); 
INSERT INTO Jogador VALUES(27,'Rômulo',20, 'Brasil','ST', 'Athletico-PR'); 
INSERT INTO Jogador VALUES(28,'Pablo',30, 'Brasil','ST', 'Athletico-PR'); 

INSERT INTO Jogador VALUES(29,'Lucas Hoyos',33, 'Argentina','GK', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(30,'Leonardo Burián',38, 'Uruguai','GK', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(31,'Matías Borgogno',24, 'Argentina','GK', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(32,'Valentín Gómez',19, 'Argentina','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(33,'Lautaro Giannetti',29, 'Argentina','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(34,'Diego Godín',36, 'Uruguai','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(35,'Matías De los Santos',29, 'Uruguai','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(36,'Miguel Brizuela',25, 'Argentina','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(37,'Damián Fernández',21, 'Argentina','CB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(38,'Francisco Ortega',23, 'Argentina','LB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(39,'Emanuel Insúa',31, 'Argentina','LB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(40,'Tomás Guidara',26, 'Argentina','RB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(41,'Leonardo Jara',31, 'Argentina','RB', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(42,'Máximo Perrone',19, 'Argentina','CDM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(43,'Santiago Cáseres',25, 'Argentina','CDM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(44,'Agustín Mulet',22, 'Argentina','CDM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(45,'Nicolás Garayalde',23, 'Argentina','CM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(46,'José Florentín',26, 'Paraguai','CM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(47,'Mateo Seoane',18, 'Argentina','CM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(48,'Franco Díaz',22, 'Argentina','CM', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(49,'Lucas Janson',28, 'Argentina','LW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(50,'Gianluca Prestianni',16, 'Argentina','LW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(51,'Jonathan Menéndez',28, 'Argentina','LW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(52,'Ricardo Centurión',29, 'Argentina','LW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(53,'Luca Orellano',22, 'Argentina','RW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(54,'Julián Fernández',18, 'Argentina','RW', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(55,'Lucas Pratto',34, 'Argentina','CF', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(56,'Walter Bou',29, 'Argentina','ST', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(57,'Abiel Osorio',20, 'Argentina','ST', 'Vélez Sarsfield');
INSERT INTO Jogador VALUES(58,'Santiago Castro',18, 'Argentina','ST', 'Vélez Sarsfield');

INSERT INTO Jogador VALUES(59,'Diego Alves',37, 'Brasil','GK', 'Flamengo');
INSERT INTO Jogador VALUES(60,'Hugo Souza',23, 'Brasil','GK', 'Flamengo');
INSERT INTO Jogador VALUES(61,'Santos',32, 'Brasil','GK', 'Flamengo');
INSERT INTO Jogador VALUES(62,'Léo Pereira',26, 'Brasil','CB', 'Flamengo');
INSERT INTO Jogador VALUES(63,'Fabrício Bruno',26, 'Brasil','CB', 'Flamengo');
INSERT INTO Jogador VALUES(64,'Pablo',31, 'Brasil','CB', 'Flamengo');
INSERT INTO Jogador VALUES(65,'Rodrigo Caio',29, 'Brasil','CB', 'Flamengo');
INSERT INTO Jogador VALUES(66,'David Luiz',35, 'Brasil','CB', 'Flamengo');
INSERT INTO Jogador VALUES(67,'Ayrton Lucas',25, 'Brasil','LB', 'Flamengo');
INSERT INTO Jogador VALUES(68,'Filipe Luís',37, 'Brasil','LB', 'Flamengo');
INSERT INTO Jogador VALUES(69,'Matheuzinho',22, 'Brasil','RB', 'Flamengo');
INSERT INTO Jogador VALUES(70,'Guillermo Varela',37, 'Uruguai','RB', 'Flamengo');
INSERT INTO Jogador VALUES(71,'Rodinei',30, 'Brasil','RB', 'Flamengo');
INSERT INTO Jogador VALUES(72,'João Gomes',21, 'Brasil','CDM', 'Flamengo');
INSERT INTO Jogador VALUES(73,'Erick Pulgar',28, 'Chile','CDM', 'Flamengo');
INSERT INTO Jogador VALUES(74,'Thiago Maia',25, 'Brasil','CDM', 'Flamengo');
INSERT INTO Jogador VALUES(75,'Éverton Ribeiro',33, 'Brasil','CM', 'Flamengo');
INSERT INTO Jogador VALUES(76,'Arturo Vidal',35, 'Chile','CM', 'Flamengo');
INSERT INTO Jogador VALUES(77,'Diego',37, 'Brasil','CM', 'Flamengo');
INSERT INTO Jogador VALUES(78,'Giorgian de Arrascaeta',28, 'Uruguai','CAM', 'Flamengo');
INSERT INTO Jogador VALUES(79,'Matheus França',18, 'Brasil','CAM', 'Flamengo');
INSERT INTO Jogador VALUES(80,'Victor Hugo',18, 'Brasil','CAM', 'Flamengo');
INSERT INTO Jogador VALUES(81,'Éverton',26, 'Brasil','LW', 'Flamengo');
INSERT INTO Jogador VALUES(82,'Bruno Henrique',31, 'Brasil','LW', 'Flamengo');
INSERT INTO Jogador VALUES(83,'Marinho',32, 'Brasil','RW', 'Flamengo');
INSERT INTO Jogador VALUES(84,'Gabriel Barbosa',26, 'Brasil','ST', 'Flamengo');
INSERT INTO Jogador VALUES(85,'Pedro',25, 'Brasil','ST', 'Flamengo');
INSERT INTO Jogador VALUES(86,'Mateusão',18, 'Brasil','ST', 'Flamengo');
INSERT INTO Jogador VALUES(87,'Hulk',36, 'Brasil','ST', 'Atlético-MG');
INSERT INTO Jogador VALUES(88,'Matías Zaracho',24, 'Argentina','CAM', 'Atlético-MG');
INSERT INTO Jogador VALUES(89,'Murilo',25, 'Brasil','CB', 'Palmeiras');
INSERT INTO Jogador VALUES(90,'Danilo',21, 'Brasil','CDM', 'Palmeiras');
INSERT INTO Jogador VALUES(91,'Michael Santos',29, 'Uruguai','ST', 'Talleres');
INSERT INTO Jogador VALUES(92,'Rodrigo Garro',24, 'Argentina','CAM', 'Talleres');

INSERT INTO Jogador VALUES(93,'Gustavo Scarpa',28, 'Brasil','CAM', 'Palmeiras');
INSERT INTO Jogador VALUES(94,'Rony',27, 'Brasil','ST', 'Palmeiras');

INSERT INTO Jogador VALUES(95,'José Correa',30, 'Colômbia','ST', 'Independiente Petrolero');





INSERT INTO Grupo VALUES('A','Palmeiras','Emelec', 'Deportivo Tachira', 'Independiente Petrolero');
INSERT INTO Grupo VALUES('B','Libertad','Athletico-PR', 'The Strongest', 'Caracas FC');
INSERT INTO Grupo VALUES('C','Estudiantes','Vélez Sarsfield', 'Nacional', 'RB Bragantino');
INSERT INTO Grupo VALUES('D','Atlético-MG','Deportes Tolima', 'Independiente del Valle', 'América-MG');
INSERT INTO Grupo VALUES('E','Boca Juniors','Corinthians', 'Deportivo Cali', 'Always Ready');
INSERT INTO Grupo VALUES('F','River Plate','Fortaleza', 'Colo Colo', 'Alianza Lima');
INSERT INTO Grupo VALUES('G','Colón','Cerro Porteño', 'Olimpia', 'Peñarol');
INSERT INTO Grupo VALUES('H','Flamengo','Talleres', 'U. Católica', 'Sporting Cristal');


INSERT INTO Fase VALUES(1,'PE','2022-02-10', '2022-03-16');
INSERT INTO Fase VALUES(2,'FG','2022-04-05', '2022-05-27');
INSERT INTO Fase VALUES(3,'OF','2022-06-28', '2022-07-08');
INSERT INTO Fase VALUES(4,'QF','2022-08-03', '2022-08-12');
INSERT INTO Fase VALUES(5,'MF','2022-08-31', '2022-09-08');
INSERT INTO Fase VALUES(6,'FI','2022-10-29', '2022-10-29');



INSERT INTO Jogo VALUES(1,'PE','2022-03-03', NULL,'Estudiantes', 'Audax Italiano', "2-0");
INSERT INTO Jogo VALUES(2,'PE','2022-03-09', NULL,'Barcelona SC', 'América-MG', "0-0");
INSERT INTO Jogo VALUES(3,'FG','2022-04-13', 'A', 'Palmeiras', 'Independiente Petrolero', "8-1");
INSERT INTO Jogo VALUES(4,'FG','2022-04-13', 'B', 'Libertad', 'Caracas FC', "2-1");
INSERT INTO Jogo VALUES(5,'FG','2022-05-18', 'C', 'Nacional', 'Vélez Sarsfield', "2-3");
INSERT INTO Jogo VALUES(6,'FG','2022-05-05', 'D', 'Deportes Tolima', 'Independiente del Valle', "1-0");
INSERT INTO Jogo VALUES(7,'FG','2022-04-27', 'E', 'Corinthians', 'Boca Juniors', "2-0");
INSERT INTO Jogo VALUES(8,'FG','2022-05-06', 'F', 'Alianza Lima', 'Colo Colo', "1-1");
INSERT INTO Jogo VALUES(9,'FG','2022-05-26', 'G', 'Peñarol', 'Colón', "2-1");
INSERT INTO Jogo VALUES(10,'FG','2022-05-18', 'H', 'U. Católica', 'Sporting Cristal', "2-1");
INSERT INTO Jogo VALUES(11,'OF','2022-06-28', NULL, 'Emelec', 'Atlético-MG', "1-1");
INSERT INTO Jogo VALUES(12,'OF','2022-07-05', NULL, 'Atlético-MG', 'Emelec', "1-0");
INSERT INTO Jogo VALUES(13,'QF','2022-08-05', NULL, 'Athletico-PR', 'Estudiantes', "0-0");
INSERT INTO Jogo VALUES(14,'QF','2022-08-12', NULL, 'Estudiantes', 'Athletico-PR', "0-1");
INSERT INTO Jogo VALUES(15,'MF','2022-08-31', NULL, 'Athletico-PR', 'Palmeiras', "1-0");
INSERT INTO Jogo VALUES(16,'MF','2022-09-07', NULL, 'Palmeiras', 'Athletico-PR', "2-2");
INSERT INTO Jogo VALUES(17,'FI','2022-10-29', NULL, 'Flamengo', 'Athletico-PR', "1-0");
INSERT INTO Jogo VALUES(18,'QF','2022-08-03', NULL, 'Corinthians', 'Flamengo', "0-2");
INSERT INTO Jogo VALUES(19,'QF','2022-08-04', NULL, 'Atlético-MG', 'Palmeiras', "2-2");
INSERT INTO Jogo VALUES(20,'QF','2022-08-04', NULL, 'Vélez Sarsfield', 'Talleres', "3-2");
INSERT INTO Jogo VALUES(21,'QF','2022-08-10', NULL, 'Flamengo', 'Corinthians', "1-0");
INSERT INTO Jogo VALUES(22,'QF','2022-10-29', NULL, 'Palmeiras', 'Atlético-MG', "0-0");
INSERT INTO Jogo VALUES(23,'QF','2022-10-29', NULL, 'Talleres', 'Vélez Sarsfield', "0-1");


INSERT INTO Evento VALUES(1,17,45);
INSERT INTO Evento VALUES(2,17,20);
INSERT INTO Evento VALUES(3,17,46);
INSERT INTO Evento VALUES(4,17,57);
INSERT INTO Evento VALUES(5,17,57);
INSERT INTO Evento VALUES(6,17,65);
INSERT INTO Evento VALUES(7,17,71);
INSERT INTO Evento VALUES(8,17,75);
INSERT INTO Evento VALUES(9,17,84);
INSERT INTO Evento VALUES(10,17,84);
INSERT INTO Evento VALUES(11,17,28);
INSERT INTO Evento VALUES(12,17,43);
INSERT INTO Evento VALUES(13,17,43);
INSERT INTO Evento VALUES(14,17,68);
INSERT INTO Evento VALUES(15,17,73);
INSERT INTO Evento VALUES(16,17,75);
INSERT INTO Evento VALUES(17,15,23);
INSERT INTO Evento VALUES(18,2,90);
INSERT INTO Evento VALUES(19,2,120);
INSERT INTO Evento VALUES(20,18,37);
INSERT INTO Evento VALUES(21,18,51);
INSERT INTO Evento VALUES(22,19,45);
INSERT INTO Evento VALUES(23,19,47);
INSERT INTO Evento VALUES(24,19,59);
INSERT INTO Evento VALUES(25,19,90);
INSERT INTO Evento VALUES(26,20,5);
INSERT INTO Evento VALUES(27,20,73);
INSERT INTO Evento VALUES(28,20,81);
INSERT INTO Evento VALUES(29,20,87);
INSERT INTO Evento VALUES(30,20,90);
INSERT INTO Evento VALUES(31,21,52);
INSERT INTO Evento VALUES(32,14,90);
INSERT INTO Evento VALUES(33,23,79);
INSERT INTO Evento VALUES(34,18,12);
INSERT INTO Evento VALUES(35,18,22);
INSERT INTO Evento VALUES(36,20,55);
INSERT INTO Evento VALUES(37,20,83);
INSERT INTO Evento VALUES(38,20,85);
INSERT INTO Evento VALUES(39,21,25);
INSERT INTO Evento VALUES(40,22,29);
INSERT INTO Evento VALUES(41,22,52);
INSERT INTO Evento VALUES(42,22,88);
INSERT INTO Evento VALUES(43,12,79);
INSERT INTO Evento VALUES(44,16,27);

INSERT INTO Evento VALUES(45,16,42);
INSERT INTO Evento VALUES(46,16,91);
INSERT INTO Evento VALUES(47,3,5);
INSERT INTO Evento VALUES(48,3,19);
INSERT INTO Evento VALUES(49,3,27);
INSERT INTO Evento VALUES(50,3,41);
INSERT INTO Evento VALUES(51,3,45);
INSERT INTO Evento VALUES(52,3,49);
INSERT INTO Evento VALUES(53,3,68);
INSERT INTO Evento VALUES(54,3,82);
INSERT INTO Evento VALUES(55,3,91);

INSERT INTO Golo VALUES(1,1,84);
INSERT INTO Golo VALUES(2,17,16);
INSERT INTO Golo VALUES(3,20,78);
INSERT INTO Golo VALUES(4,21,84);
INSERT INTO Golo VALUES(5,22,87); 
INSERT INTO Golo VALUES(6,23,88); 
INSERT INTO Golo VALUES(7,24,89); 
INSERT INTO Golo VALUES(8,25,90); 
INSERT INTO Golo VALUES(9,26,49);
INSERT INTO Golo VALUES(10,27,49);
INSERT INTO Golo VALUES(11,28,91);
INSERT INTO Golo VALUES(12,29,92);
INSERT INTO Golo VALUES(13,30,54);
INSERT INTO Golo VALUES(14,31,85);
INSERT INTO Golo VALUES(15,32,26);
INSERT INTO Golo VALUES(16,33,54);
INSERT INTO Golo VALUES(17,43,87);

INSERT INTO Golo VALUES(18,45,16);
INSERT INTO Golo VALUES(19,46,16);
INSERT INTO Golo VALUES(20,47,95);
INSERT INTO Golo VALUES(21,48,94);
INSERT INTO Golo VALUES(22,49,94);
INSERT INTO Golo VALUES(23,50,93);
INSERT INTO Golo VALUES(24,51,94);
INSERT INTO Golo VALUES(25,52,94);
INSERT INTO Golo VALUES(26,53,93);
INSERT INTO Golo VALUES(27,54,93);
INSERT INTO Golo VALUES(28,55,94);

INSERT INTO Substituicao VALUES(1,2,67,68);
INSERT INTO Substituicao VALUES(2,3,5,16);
INSERT INTO Substituicao VALUES(3,4,22,25);
INSERT INTO Substituicao VALUES(4,5,27,20);
INSERT INTO Substituicao VALUES(5,6,28,26);
INSERT INTO Substituicao VALUES(6,7,76,74);
INSERT INTO Substituicao VALUES(7,8,19,11);
INSERT INTO Substituicao VALUES(8,9,81,84);
INSERT INTO Substituicao VALUES(9,10,80,78);

INSERT INTO Falta VALUES(1,11,3,'Y');
INSERT INTO Falta VALUES(2,12,16,'Y');
INSERT INTO Falta VALUES(3,13,3,'Y');
INSERT INTO Falta VALUES(4,14,78,'Y');
INSERT INTO Falta VALUES(5,15,27,'Y');
INSERT INTO Falta VALUES(6,16,76,'Y');
INSERT INTO Falta VALUES(7,34,74,'Y');
INSERT INTO Falta VALUES(8,35,71,'Y');
INSERT INTO Falta VALUES(9,36,32,'Y');
INSERT INTO Falta VALUES(10,37,41,'Y');
INSERT INTO Falta VALUES(11,38,57,'Y');
INSERT INTO Falta VALUES(12,39,62,'Y');
INSERT INTO Falta VALUES(13,40,90,'R');
INSERT INTO Falta VALUES(14,41,88,'Y');
INSERT INTO Falta VALUES(15,42,87,'Y');
INSERT INTO Falta VALUES(16,43,16,'Y');


INSERT INTO Prolongamento VALUES(1,18,"0-0","0-0");

INSERT INTO Penaltis VALUES(1,19,"0-0","4-5");


INSERT INTO Resultados VALUES(1, 'Palmeiras', 'FG', 18, 6, 0, 0, 25, 3, 'N');
INSERT INTO Resultados VALUES(2, 'Palmeiras', 'MF', NULL, 0, 1, 1, 2, 3, 'N');
INSERT INTO Resultados VALUES(3, 'América-MG', 'PE', NULL, 1, 2, 1, 3, 3, 'N');
INSERT INTO Resultados VALUES(4, 'Libertad', 'FG', 10, 3, 1, 1, 8, 6, 'N');
INSERT INTO Resultados VALUES(5, 'RB Bragantino', 'FG', 5, 1, 2, 2, 5, 9, 'N');
INSERT INTO Resultados VALUES(6, 'U. Católica', 'FG', 4, 1, 1, 4, 5, 10, 'N');
INSERT INTO Resultados VALUES(7, 'Nacional', 'FG', 7, 2, 1, 2, 7, 7, 'N');
INSERT INTO Resultados VALUES(8, 'Athletico-PR', 'FI', NULL, 0, 0, 1, 0, 1, 'N');
INSERT INTO Resultados VALUES(9, 'Flamengo', 'FI', NULL, 1, 0, 0, 1, 0, 'Y');